apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ include "float_exporter.fullname" . }}-config
  labels:
    {{- include "float_exporter.labels" . | nindent 4 }}
data:
  float_exporter.yml: |
    email: "{{ required "A valid .Values.email entry required!" .Values.email }}"
    user_agent: "{{ .Values.userAgent }} {{ .Chart.AppVersion }}"
    log_level: "{{ .Values.logLevel }}"
    port: {{ .Values.service.port }}
    report_days: {{ .Values.reportDays }}

