apiVersion: v1
kind: Secret
metadata:
  name: {{ include "float_exporter.fullname" . }}-secret
  labels:
    {{- include "float_exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLOAT_ACCESS_TOKEN: {{ required "A valid .Values.accessToken entry required!" .Values.accessToken }}

