apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  namespace: monitoring
  labels:
    app: fe-app
spec:
  ports:
  - port: 9709
    targetPort: 9709
    protocol: TCP
  selector:
    app: fe-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-dep
  namespace: monitoring
  labels:
    app: fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: fe-configmap
      containers:
        - name: float-exporter
          image: tobiasbp/float_exporter:latest
          ports:
            - containerPort: 9709
          volumeMounts:
            - name: config-volume
              mountPath: /etc/float_exporter.yml
              subPath: float_exporter.yml
          env:
            - name: FLOAT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: FLOAT_ACCESS_TOKEN  
